# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0829a48d3bb4f784c5dd060fbfd7f1b28cece8ba1edf2234b14ffeef049779e3284d1cf8b9d330578d9110a15be3eef3041eb39994057bef69d146553280c315

test:
  secret_key_base: a019850d27aff1e2e4127be22996a32ea6368be006fabcb908ef93040235028a240cbede4295ca730e440a21af89198a18dc8e7e1d633972cd9b6ee6a9faa5eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
